### ISSUE TITLE
Ch3 - diagrams overlap when browser resized

### ISSUE THREAD

**Issue by redblobgames** [aimacode/aima-javascript#105]
Go through all the sections of chapter 3 and make sure they work at different browser widths. The page uses Bootstrap but if it's cleaner to do without Bootstrap (e.g. flexbox or css grids), that would be fine.

Screenshots:

<img width="487" alt="screen shot 2017-09-10 at 16 44 20" src="https://user-images.githubusercontent.com/8757369/30254058-6d6175fe-9647-11e7-9129-b43e11062a29.png">
<img width="735" alt="screen shot 2017-09-10 at 16 44 32" src="https://user-images.githubusercontent.com/8757369/30254061-6d6f93a0-9647-11e7-8d10-42312837db93.png">
<img width="523" alt="screen shot 2017-09-10 at 16 44 38" src="https://user-images.githubusercontent.com/8757369/30254060-6d6f41de-9647-11e7-9d85-3151126b1e7b.png">
<img width="913" alt="screen shot 2017-09-10 at 16 44 53" src="https://user-images.githubusercontent.com/8757369/30254059-6d6f2c30-9647-11e7-9f78-d36f0135c8e4.png">

**Comment by redblobgames** [comment]
The SVG `viewBox` parameter is sometimes useful here. You can design the diagram for a given size, and put that size into the `viewBox`. Then if the SVG is resized, it still keeps the original coordinate system that `viewBox` specifies.

**Comment by Rishav159** [comment]
I am on it.

**Comment by OmarShehata** [comment]
Is anyone still working on this? @Rishav159

**Comment by Rishav159** [comment]
@OmarShehata You can take over if you like :) I have been a little busy.

**Comment by OmarShehata** [comment]
I'd love to jump on this as a way to familiarize myself with the project and get a first contribution in!
