### ISSUE TITLE
Ch 22 - language classification demo misbehaves when pressing Enter

### ISSUE THREAD

**Issue by redblobgames** [aimacode/aima-javascript#112]
In the language classification demo, type some text and press Enter instead of clicking the button. The page erases the text and reloads instead of running the classification. I believe this is because the html specifies a `<form>` and form submission goes back to the server by default. Either make form submission trigger the classification, or take out the `<form>`.

**Comment by OmarShehata** [comment]
I'd like to take this! Perhaps as a warm up for further developing this chapter.

**Comment by redblobgames** [comment]
@OmarShehata Great! Note that @prakamya-mishra is also working on this chapter right now.

**Comment by OmarShehata** [comment]
Ah, thanks for the heads up! I'll wait and keep watching the progress on this chapter then and see if there are other specific things I could help with.
