### ISSUE TITLE
Ch1- Introduction

### ISSUE THREAD

**Issue by prakamya-mishra** [aimacode/aima-javascript#129]
I would like to work on Ch 1- Introduction also.
@redblobgames is it okay if I complete this first and then continue working with ch-22?

**Comment by redblobgames** [comment]
Chapter 1 is mostly about history. What kinds of diagrams are you thinking about for chapter 1?

**Comment by prakamya-mishra** [comment]
I was thinking of making some kind of flowchart of how AI evolved for 1.3) THE HISTORY OF ARTIFICIAL INTELLIGENCE

**Comment by redblobgames** [comment]
My guess is that such a flowchart would be nice to include in the book, but doesn't benefit much from interactive elements. It might be better to put it in the book directly instead of putting it on the website.
