### ISSUE TITLE
We should use two.js to make the visualizations.

### ISSUE THREAD

**Issue by Ghost---Shadow** [aimacode/aima-javascript#13]
https://jonobr1.github.io/two.js/

two.js is a very popular javascript graphics library. It is used a lot in chrome experiments. It supports WebGL which we might need if we make a any visualizations with large number of sprites. 

https://www.chromeexperiments.com/

**Comment by norvig** [comment]
two.js looks pretty good. I've heard recommendations for other packages as well, such as d3.js. I don;t know enough to choose between them; happy to see what you come up with,
