### ISSUE TITLE
Add Visualization for 8-Queen Problem

### ISSUE THREAD

**Issue by Dragneel7** [aimacode/aima-javascript#134]
The 8-Queen problem is a excellent example that proves not only a good searching example but also as a an example in the list of problems solved using genetic algorithms. So maybe we can add it.
I am note sure in which chapter should it go as it is mentioned in chapter3, 4, 6.
@redblobgames what do you think?

**Would like to work on it :** Yes.

**Comment by redblobgames** [comment]
Sure, go for it. I think the 8-Queen problem is probably better for chapter 4 or 6. We have lots of search visualizations in chapter 3 already. We could use more visualizations of the techniques in chapter 4 and 6 :-)

**Comment by Dragneel7** [comment]
I will start working on it.

**Comment by Dragneel7** [comment]
@redblobgames Hi, I have decided to put this visualization in chapter 6 under subheading "Minimum-Conflict" in reference to the book. As of now I have completed the algorithm of the function and am thinking of using "http://chessboardjs.com/" to make the chessboard. It is a free opensource js library under MIT License. But doing so requires me to write a small amount of javascript within the html file and c_minConflicts.js which is responsible for visualisation will become redundant.
Can I follow the above mentioned as it is much easier but the only problem is that it breaks the code consistency?

**Comment by Dragneel7** [comment]
@redblobgames Please review the PR. I have a bit of trouble in the code which i would like to clarify. 
Thanks.

**Comment by Anisha1234** [comment]
Hello,
I have worked on the 8-Queen problem which is hosted [here](https://anisha1234.github.io/blog-2.html).
I went through all the suggestions and recommendations from @redblobgames  and @samuelgoto from the docs and have come up with it.
I agree with the previous contributors regarding the suggestion to let the user fiddle with the problem itself before presenting the solution to solve the problem. In the blog, we first present the user with a chessboard and ask to put 8 queens on the board without conflict. Whenever there is a conflict, we provide feedback through a red line showing which queens are in conflict. This will allow the user to understand the problem statement before jumping to the solution.
Next, we abstract the problem by providing visual feedback as to which positions are no longer possible for queens, once a queen has been placed. This will allow the user to look at the problem with a different view. This is a build-up before presenting the backtracking search method to solve the problem. As the blog mentions, most of the users will try to randomly place queens and then change the positions of already placed queen once all the cells are finished. This will provide the user with necessary intuition regarding the algorithm.
I have not completed the visualizations yet (backtracking search and some finishing touches). I will be glad if you could provide some feedback. I would like to include these visualizations in the project as PR.
This also serves as a showcase for design skills as required by GSOC for aimacode-javascript.
Please provide suggestions!
Thanks in advance.

**Comment by Dragneel7** [comment]
@Anisha1234 That is nice work. I have a suggestion for the min-conflict visualization. The algorithm starts by assigning random values and then minimizes the conflicts step by step. So you can start by random arrangement of 8 Queens and then the show the reader where the queen he selects(as you have done now).

**Comment by samuelgoto** [comment]
Can you kick off a design doc and send this to us in this thread? It is very hard for us to comment/collaborate/iterate on your design in the form of a HTML/JS/CSS prototype.

Start with a design doc (recommendation: use google docs and google diagrams in it) to lay out your narrative, bigger diagrams, get some feedback and when you have something solid you move on to a prototype.

Please follow [this](https://github.com/aimacode/aima-javascript/wiki/GSOC-2018#bonus-points-show-us-a-sample-of-your-best-work) process.

**Comment by redblobgames** [comment]
Closing as this seems inactive
