### ISSUE TITLE
Add sticky footer and remove horizontal scroll

### ISSUE THREAD

**Issue by utkarsh23** [aimacode/aima-javascript#139]
I've noticed the following *two* issues.
* **I think its better if we have a sticky footer for the index page**
![ss](https://user-images.githubusercontent.com/12075549/34460907-9ade833e-ee42-11e7-9dba-9f063c07122c.png)

* **Remove horizontal scroll**
![ss](https://user-images.githubusercontent.com/12075549/34467469-dbf9ec56-ef18-11e7-845f-a93b913c7a90.png)

I'd like to take up this issue

**Comment by redblobgames** [comment]
These look like two separate issues.

For web design features like sticky footers, we are waiting for someone who is working on the web design part of this project (come to the gitter if you want to chat more), so I recommend not spending much time on this until you can talk to that person (once they join the project).

For the scrollbar, it is a bug - please file it as a separate github issue so we can track bug fixes and feature requests separately. Thanks!

**Comment by utkarsh23** [comment]
Alright that's cool :)
