### ISSUE TITLE
Introduction page is blank

### ISSUE THREAD

**Issue by Dragneel7** [aimacode/aima-javascript#143]
The introduction page is completely blank. I Believe it should give some information about the book and what its aims are.

**Comment by redblobgames** [comment]
It probably depends on how AIMA intends to use this site. It's possible they'll integrate the visualizations into the book's site, instead of keeping this as a standalone site. I don't know.

**Comment by redblobgames** [comment]
Happy to discuss more on the [gitter chat](https://gitter.im/aimacode/Lobby)
