### ISSUE TITLE
A design idea for chapter 17: Making Complex Decissions

### ISSUE THREAD

**Issue by kUSHAL0601** [aimacode/aima-javascript#160]
@samuelgoto , I was planning to work on the design of the MDP networks and take on designing the Automated Vacuum Cleaner problem in POMDP. I am working on both the design docs. Let me know your idea about it. Let me know if you want any specific example for MDP, or I will be working with the table form itself.

**Comment by redblobgames** [comment]
I am closing this assuming this is not being worked on. If you are still working on this, feel free to reopen.
