### ISSUE TITLE
Localization in partially observable Environment

### ISSUE THREAD

**Issue by Rishav159** [aimacode/aima-javascript#161]
Hello,
During my last few days of GSoC last year, I was working on a visualization for localization in the partially observable environment from Chapter 4 (Beyond Classical Search). I am considering completing that visualization.
I see that aima-javascript has changed a bit since last year (For instance, as of last year, we were expected to create visualizations as a supplement with the book and were free to assume that the user already has the book, but it seems like this year, the focus is on creating standalone tutorials). Due to this, I was wondering if that visualization is still useful.
I would create a PR with the current progress. 
Kindly review and tell if the diagram is still useful for aima and should I go ahead and complete it.
Thanks!

**Comment by redblobgames** [comment]
Looks like Peter merged this even though you wrote "do not merge". I'm going to close this issue for now. The direction continues to be away from individual diagrams and towards explanations.
