### ISSUE TITLE
Missing CONTRIBUTING.md file

### ISSUE THREAD

**Issue by mayankDhiman** [aimacode/aima-javascript#167]
I feel that new contributors are facing a problem as there is no CONTRIBUTING.md file in this repository. 
Though there is a well maintained CONTRIBUTING.md file in aima-python repository but problem arrises for new comers desiring to contribute in other repositories. 
Thus, there is a need for adding a CONTRIBUTING.md file in other repositories too to guid new contributors.

**Comment by redblobgames** [comment]
It's true, there's no CONTRIBUTING.md file. In the meantime, the contribution instructions are [linked](https://github.com/aimacode/aima-javascript/wiki/How-to-Contribute) from the README.md file.

**Comment by redblobgames** [comment]
Ok, I've added one but it just points to the wiki.
