### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by redblobgames** [aimacode/aima-javascript#172]
`.babelrc`, `Gulpfile.babel.js`, `package.json` are obsolete. These were used in 2016 but are no longer being used as of 2017. First, check with the project maintainer (either Sam or Peter) to confirm that there are no plans to use these, then remove these files.

**Comment by parammittal16** [comment]
@redblobgames happy to do this. @samuelgoto @norvig shall i remove these files ?
