### ISSUE TITLE
Project proposals - GSoC 2019

### ISSUE THREAD

**Issue by samuelgoto** [aimacode/aima-javascript#174]
Hey all, here is the list of the open proposals for GSoC 2019 (proposals for [2018](https://github.com/aimacode/aima-javascript/issues/158)) that I'm going through in this format with [these guidelines](https://docs.google.com/document/d/1gmJ_dObUvndAFPowP3Ah8MOhG1q4Um2CM4o2JMmznCc/).

Please add yours here (create a comment on this thread with a link to your design doc / prototype).

I'll use this thread here as an opportunity for everybody to: (a) know what others are working on, (b) get inspiration from other's proposals and (c) see what patterns of comment/feedback occurs.

Importantly, I'll also use this list to organize myself and make sure no proposal falls through the cracks. Hopefully, this also makes @redblobgames 's life easier too to help steer the designs in the right direction :)

This list is sorted arbitrarily. The status bit shows on whose court the ball is.

| Student  | Design Doc | Prototype | Status |
| ------------- | ------------- |  ------------- | ------------- |
| @namanZelawat   | [design doc](https://docs.google.com/document/u/1/d/16wGAUBiLRvs-TYdQTzjjT5urBDNQNhawBblonXYYlq0/edit#heading=h.1drh6bzbpey8) ch13 | Prototype | on mentor |
| @vishal260700 | [design doc](https://docs.google.com/document/d/1_-ndkRXo0kNOnjnmeTvTrCz1sBO0p_NEsQreTcCAwjU/edit) ch4 | [prototype](https://vishal260700.github.io/prototype/NEAT/) | on student |
| @ashwinvaidya17 | [design doc](https://docs.google.com/document/d/10Q-Obisz1Ix7ylWUHDTNrlUR3ruZQExpavyH-al1qhE/edit#heading=h.jy16btw9ivt1) ch21 | prototype | on mentor |
| @savvysiddharth | [design doc](https://docs.google.com/document/d/1D8toMLQ7NvIPuZ6xSwSEKj20ny9JWxHxlc8U5JGNOa8/edit#heading=h.o8lvkghzjezz) ch4 | [prototype](https://savvysiddharth.github.io/prototype-gsoc/) | on mentor |
| @kareemalsawah  | [design doc](https://docs.google.com/document/d/1ViUsiJdA9CNVbV9oVQ9NUWx0WLVnvpwXLyA_YOl0pqA/edit) ch18 | [prototype](https://kareemalsawah.github.io/Linear_Regression_Demo/) | on mentor |
| @KanakalathaVemuru | [design doc](https://docs.google.com/document/d/1GuZo1sUaAtyJkMXppb397GqWaWIRUFxDPaOJUvE9Eig/edit?usp=drivesdk) ch17,21 | [prototype](https://kareemalsawah.github.io/Intro_to_machine_learning/) | on student |
| @jasmaa | [design doc](https://docs.google.com/document/d/15xQeYCdsgWQExhzr2Jr1bFe-H0ZNBTYtRsLGW2DCM_A/edit?usp=sharing) ch24 | [prototype](https://jasmaa.github.io/demos/aimacodejs2019/) | on mentor | 
| user | design doc | prototype | status |

Ping this thread if/when you are ready to share your design docs with me or need me to review them again.

**Comment by samuelgoto** [comment]
@NamanZelawat that's a pretty awesome proposal, thanks for putting that together! I added that to the table and signaled that the action is on my side now. I'll take a look at your design doc and we can go from there.

**Comment by NamanZelawat** [comment]
Thank you, sir .

**Comment by Vishal260700** [comment]
Hello Sam, this is my [proposal](https://drive.google.com/open?id=1_-ndkRXo0kNOnjnmeTvTrCz1sBO0p_NEsQreTcCAwjU) document for NeuroEvolution Algorithm and the [prototype](https://vishal260700.github.io/prototype/NEAT/). Please review it and suggest add-ons.

**Comment by ashwinvaidya17** [comment]
Hello @samuelgoto this is my [proposal](https://docs.google.com/document/d/10Q-Obisz1Ix7ylWUHDTNrlUR3ruZQExpavyH-al1qhE/edit?usp=sharing) for part 5, reinforcement learning. Please review it and suggest any changes or corrections.

**Comment by savvysiddharth** [comment]
Hello @samuelgoto, please take a look at my [proposal](https://docs.google.com/document/d/1D8toMLQ7NvIPuZ6xSwSEKj20ny9JWxHxlc8U5JGNOa8/edit?usp=sharing), and give me suggestions if possible. I've partially implemented a few diagrams for the [prototype](https://savvysiddharth.github.io/prototype-gsoc/).

**Comment by kareemalsawah** [comment]
Hello @samuelgoto, this is my [proposal](https://docs.google.com/document/d/1ViUsiJdA9CNVbV9oVQ9NUWx0WLVnvpwXLyA_YOl0pqA/edit?usp=sharing) for Chapter 18 "Learning from examples". This is my [prototype](https://kareemalsawah.github.io/Linear_Regression_Demo/) for one of the demos (demo 5) in my proposal. Any suggestions would be appreciated. Thanks in advance.

**Comment by KanakalathaVemuru** [comment]
Hello @samuelgoto, this is my [design document](https://docs.google.com/document/d/1GuZo1sUaAtyJkMXppb397GqWaWIRUFxDPaOJUvE9Eig/edit?usp=drivesdk) for chapter 17 & 21. Please review it and suggest any corrections or changes. Thanks in advance.

**Comment by samuelgoto** [comment]
Alright, I took an initial pass at all design docs / prototypes in this list. Ball on your side of court now.

**Comment by samuelgoto** [comment]
I just took another pass at these design docs, wherever progress was made.

**Comment by savvysiddharth** [comment]
@samuelgoto I made changes as you suggested earlier, I didn't get your comment this time, If possible can you take a look at my [design doc](https://docs.google.com/document/d/1D8toMLQ7NvIPuZ6xSwSEKj20ny9JWxHxlc8U5JGNOa8/edit?usp=sharing)?

**Comment by jasmaa** [comment]
Hello @samuelgoto. Here are my [design doc](https://docs.google.com/document/d/15xQeYCdsgWQExhzr2Jr1bFe-H0ZNBTYtRsLGW2DCM_A/edit?usp=sharing) and [prototype](https://jasmaa.github.io/demos/aimacodejs2019/). It would help me out if you took a look at them. Thanks.

**Comment by kareemalsawah** [comment]
I have made changes to my [design doc](https://docs.google.com/document/d/1ViUsiJdA9CNVbV9oVQ9NUWx0WLVnvpwXLyA_YOl0pqA/edit) but they were not reviewed. I also changed my [prototype to this](https://kareemalsawah.github.io/Intro_to_machine_learning/) to match my new design doc.
