### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-javascript#25]
I'm new to gh-pages, so I don't understand how it woeks.
- Does it have to be re-generated every time there is a change to master branch?
- How do I see the resulting pages?

**Comment by norvig** [comment]
I see; the answer to (2) is http://aimacode.github.io/aima-javascript/

**Comment by kepta** [comment]
@norvig we should all discuss before you merge a PR. 

It's good to get a PR reviewed before it gets merged.

**Comment by kepta** [comment]
@norvig you need to run
`gulp bundle`
then
`gulp deploy`

to deploy gh-pages.

**Comment by norvig** [comment]
Thanks!

**Comment by Ghost---Shadow** [comment]
If you are still having problems, you should take a look at [this](https://github.com/shinnn/gulp-gh-pages/issues/87).

**Comment by norvig** [comment]
@kepta, I've done a bunch of npm installs, and I think I have all the deprecated packages updated, but I still get "No gulpfile found". Can you give me complete instructions and how to do gulp bundle/deploy? Thanks!

**Comment by Ghost---Shadow** [comment]
You should try re cloning the project, maybe one of the config files got corrupted.

**Comment by redblobgames** [comment]
We are no longer using gulp for gh-pages, so I'm closing this issue for now. We can revisit if we use gulp for gh-pages in the future.
