### ISSUE TITLE
Requiring external module babel-register takes a long time

### ISSUE THREAD

**Issue by Ghost---Shadow** [aimacode/aima-javascript#26]
I am new to gulp, whenever I run `gulp SOME_TASK` it says "require external module babel-register". This takes a solid 20 seconds or so. The actual task takes milliseconds to complete.

What is happening here? How do I fix it? What is this babel-register?

I tried `npm install babel-register` and also tried installing `npm3`. It did not fix the problem.

I followed [this](https://www.youtube.com/watch?v=LmdT2zhFmn4&list=PLv1YUP7gO_viROuRcGsDCNM-FUVgMYb_G) youtube tutorial series, this guys does the same thing a bit differently than what we are doing. The task completes in microseconds.

**Comment by norvig** [comment]
Can you say what you learned from the tutorial?

**Comment by Ghost---Shadow** [comment]
The tutor did not use `jspm.bundleSFX` he used a function called `uglify`

**Comment by norvig** [comment]
I too am having a hard time setting up gulp.

**Comment by Ghost---Shadow** [comment]
I researched gulp and npm a bit more, the problems seems to stem from [ES2015].(https://babeljs.io/docs/learn-es2015/)

I dont know if we are using it anywhere. In the mean time, I will try to safely remove it and see if it fixes the problem.

**Comment by Ghost---Shadow** [comment]
@redblobgames Why did you close this?

**Comment by redblobgames** [comment]
@Ghost---Shadow Oh, you're right, I shouldn't have closed this.

**Comment by redblobgames** [comment]
We haven't been using gulp for a few months now so I'm closing this. We can re-open if we start using gulp again and run into the problem.
