### ISSUE TITLE
We should use code mirror.

### ISSUE THREAD

**Issue by Ghost---Shadow** [aimacode/aima-javascript#29]
Using [Code mirror](https://codemirror.net/) readers would be able to modify the javascript on the fly while reading. The changes would be reflected back in the visualization. Something like IPython Notebook. 

What do you guys think?

**Comment by GiriB** [comment]
@Ghost---Shadow  I think the first phase would be to complete all the chapters. After that, we could add Code Mirror. It's not a necessity, more like a feature.

**Comment by Ghost---Shadow** [comment]
That is why I closed it. Too much hassle.
