### ISSUE TITLE
How to Contribute or Developer Documentation? 

### ISSUE THREAD

**Issue by umgupta** [aimacode/aima-javascript#32]
Hey, is there a document which I can refer to get started with this?
I would like to contribute to this project. If there is no such document, I could start with creating that doc itself.

**Comment by norvig** [comment]
Hi @umgupta I'm glad you're interested. Most of the action right now is in aima-python and aima-java; we could certainly use help in javascript!

**Comment by umgupta** [comment]
Yes, I know they have got the GSOC attention. However, I am more interested in creating nice visualizations. 
I have some experience with JS libraries (BackBone, React) and creating Single Page applications(SPA). I also have some experience with setting up a SPA project (I see a post where this was being discussed).

I think I can work on this but how should I start? Do you have any guideline as to how things should be done and what is to be done ? 

I would be happy to start right away, if you could give some pointers.

**Comment by Ghost---Shadow** [comment]
I have thought of a naive method of just distributing chapters to everyone.
https://github.com/aimacode/aima-javascript/issues/27

**Comment by shubhrajodiya** [comment]
@norvig 
Hello Sir,
I am interested in implementation of AIMA in javascript and visualization of algorithms in it. Can you please guide me how I can start with it.
Thanks

**Comment by Ghost---Shadow** [comment]
@shubhrajodiya 
For setting up you should read [the main page](https://github.com/aimacode/aima-javascript).
Visit the [static hosted site](http://aimacode.github.io/aima-javascript/) to get a feel for it.
Check the current contribution status over [here](https://github.com/aimacode/aima-javascript/blob/master/CONTRIBUTION.md)
Post whatever you are interested in, over [here](https://github.com/aimacode/aima-javascript/issues/27)
