### ISSUE TITLE
Proposing a new IRC Channel to discuss ideas and guide new comers

### ISSUE THREAD

**Issue by Rishav159** [aimacode/aima-javascript#44]
With the GSOC approaching, more and more participants will need guidance. I feel there should be an IRC channel for this purpose. We can discuss new ideas and get to know each other in such a platform.
What do you guys say ?

**Comment by Ghost---Shadow** [comment]
I am unfamiliar with the process of creating an IRC. You should take the impetus.

**Comment by Rishav159** [comment]
Okay. I will set it up for this repository and provide the link here.

**Comment by vamshi9** [comment]
Thank you @Rishav159 for coming up with this.

**Comment by Rishav159** [comment]
I have created a new IRC Channel on the freenode server. The channel name is '#aima-js'.
I suggest moving informal communications there.
Also, is anybody here who knows whether AIMA will be participating in GSOC 2017? I sent a message to the mailing list of the previous year GSOC group too. There is no reply from anyone.

**Comment by vamshi9** [comment]
@Rishav159  I've contacted one of the GSoCers(aima) and he said that most of the action will be in java and python for GSoC. It is better to wait till the list of organizations comes out!

**Comment by Rishav159** [comment]
@vamshi9  Thank you for that information. I wonder why javascript is not considered. Javascript provides a very flexible visualizations and being on the web platform actually makes the visualizations easily available.   Also, there is a lot of work pending in this repository. 
Anyways, I hope they consider Javascript.

**Comment by vamshi9** [comment]
I have been preparing myself with MEAN stack architecture to contribute to this repo but when I heard this I was bit disappointed but the point here is that may be norvig is considering to complete python and java as there are numerous libraries for AI in those programming languages and people are preferring these over javascript as per 2016. When times come for JS he will include this for sure atleast hope so!  
And I have a question here. Why did he ask us not to use Node.js ?

**Comment by Rishav159** [comment]
@vamshi9 I agree with you. Because there are lots of libraries for AI in Java and python, people may be preferring them over Javascript. 
Did he ask about not using Node.js ? I did not know about that. I guess we don't really need it because all the algorithms and their corresponding visualization code can be implemented in the front-end javascript itself. I am just guessing.

**Comment by Rishav159** [comment]
Now that a gitter lobby is created [here](https://gitter.im/aimacode/Lobby). This issue should be closed.

**Comment by Ghost---Shadow** [comment]
@Rishav159 Add the link to the `Readme.md` for others to know.
