### ISSUE TITLE
JS minification introduces errors

### ISSUE THREAD

**Issue by merovingienne** [aimacode/aima-javascript#48]
Bundling with default settings introduces an error to the main.js file for some reason.

In current configuration, Gulpfile.babel.js has `minify:true` in the jspm.bundleSFX method. With this, the page throws an `Uncaught ReferenceError: Invalid left-hand side expression in postfix operation`. This causes all styling and js to be lost.

Setting `minify:false` before bundling seems to fix the error and then everything loads fine. Apparently the minification breaks something.

Has anyone else come across this issue?

**Comment by Ghost---Shadow** [comment]
I have had about half a dozen issues with gulp but not this one. Some missing semicolon somewhere might be causing this problem, I think. I am not sure.

**Comment by redblobgames** [comment]
@merovingienne Are you still having this issue?

**Comment by merovingienne** [comment]
Just did a clean installation and voila! Works normally.

**Comment by redblobgames** [comment]
@merovingienne I've checked in a change that loads Bootstrap from CDN instead of making our own minified copy so this kind of problem should not happen anymore.
