### ISSUE TITLE
Greedy best first search

### ISSUE THREAD

**Issue by preethi26** [aimacode/aima-javascript#49]
greedy best first search search has been mentioned in the book but not implemented. I would like to implement it. Shall I proceed ?

**Comment by Ghost---Shadow** [comment]
Please put all your requests at [this thread](https://github.com/aimacode/aima-javascript/issues/27).
Greedy Best First Search falls under chapter 3. Currently 3 people are working on it. You should find something people are not working on currently.

**Comment by preethi26** [comment]
Thank you.
