### ISSUE TITLE
Starting point for GSoC 2017

### ISSUE THREAD

**Issue by meghanagupta3** [aimacode/aima-javascript#51]
Hello.
AIMA is one of the participating organisations for GSoC 2017, and some of the project proposals involve working on visualisations for aima-javascript (http://aima.cs.berkeley.edu/gsoc-ideas.html). Since I've followed this textbook for one of my university courses, I'd like to work on the javascript side of the code base.

I tried following the thread on Issue #27 [](https://github.com/aimacode/aima-javascript/issues/27), but I'm new to this group and am not sure what would be an appropriate place to get started for a few initial pull requests/commits.

Though I do not have a lot of experience with javascript visualisations, I can pick it up quite quickly and contribute a substantial amount in the next week or so. Moreover, I would love to contribute working code examples as well. Could anyone help me with a place to get started?

**Comment by Ghost---Shadow** [comment]
Implement any algorithm from any chapters which is not being worked upon. This is to prevent people from working on the same thing and wasting their time.

While writing the code, keep in mind that it needs some kind of "handles" for the visualizer to use. [Chapter 2](https://github.com/aimacode/aima-javascript/tree/master/2-Intelligent-Agents) is probably the simplest example. If for some reason, having handles is difficult you can also save all the steps in an array and make the visualizer play the states as a movie. [As I have done in Chapter 4](http://aimacode.github.io/aima-javascript/6-Constraint-Satisfaction-Problems/). There are more examples which you can browse from the repository.

**Comment by redblobgames** [comment]
We now have a wiki; let's use the contribution guide there. https://github.com/aimacode/aima-javascript/wiki
