### ISSUE TITLE
STEM C Studio

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-javascript#66]
Somebody made this: https://www.stemcstudio.com/#/gists/8dce0d766640e1439387fe8956f758d4

Is this Stem C Studio a tool we want to use?

**Comment by Ghost---Shadow** [comment]
Our solutions can be ported easily to this platform if we wanted to. Other than that, there is little point in changing technologies. I do not see any benefits to this. 

Also, if STEMC (for some reason) change their business model, it might be quite problematic.

**Comment by redblobgames** [comment]
I agree with @Ghost---Shadow . Our immediate goal is the visualizations and not a tool for our readers to make visualizations, and I don't see this being useful right now. If we later want to add something where readers are editing the code, there are lots of options for online editing.
