### ISSUE TITLE
About using the projects feature in Github

### ISSUE THREAD

**Issue by Ghost---Shadow** [aimacode/aima-javascript#91]
I just noticed a Projects tab in Github. (Sorry, I didnt notice it before) I played around with it and it is kind of interesting. I think we should give it a try for the sake of experimentation. Perhaps we might end up liking it.

What do you all think?

**Comment by Rishav159** [comment]
I like the idea.

**Comment by redblobgames** [comment]
Yes, it's interesting, especially for medium sized projects with many tasks to keep track of. Trello is the more popular version. I think it'd be more useful for aima-javascript if the project were more active, but right now it's basically just one person implementing visualizations.
