### ISSUE TITLE
Add table of contents and links to sections

### ISSUE THREAD

**Issue by redblobgames** [aimacode/aima-javascript#98]
For chapters that are more than one screenful, add a table of contents at the top that links to each of the sections.

**Comment by Rishav159** [comment]
Sounds like a nice idea. If anyone else wants to do it, they can take this up or else I will be turning my focus towards this near the last week of GSoC.

**Comment by prakamya-mishra** [comment]
I will try to do it. is it ok?

**Comment by Rishav159** [comment]
@prakamya-mishra Sure.

**Comment by prakamya-mishra** [comment]
I have given a PR . if it looks good then I will implement it to all the chapters.

**Comment by prakamya-mishra** [comment]
Now I will add this to all other  chapters.

**Comment by prakamya-mishra** [comment]
I have applied it to all the chapters with this problem in PR -#100.
